INVALID = -1
TERMINAL = 0
BLOCK = 1
ID_LIST = 2        # [id_1, id_2, ...]
EXPR_LIST = 3      # [expr_1, expr_2, ...]
ARG_LIST = 4       # [arg_1, arg_2, ...]
KEYVALUE_LIST = 5  # [kv_1, kv_2, ...]
FROM_IMPORT = 6    # [id, idlist]
IMPORT = 7         # [idlist]
FOR = 8
WHILE = 9
IF = 10
ELIF = 11
ELSE = 12
CLASS = 13
METHODS = 14
TUPLE = 15
OPERATOR = 16

